on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3
    - name: Setup test database
      run: |
        bin/rails db:create db:migrate
    - name: Run tests
      run: |
        bundle exec rake
        # bundle exec rspec spec/system/articles_spec.rb || echo continue
    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: my-artifact
    #     # https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions
    #     path: |
    #       tmp/screenshots/*
    #       doc/screenshots/*
    #       log/*
